import { Validator } from '@seriousme/openapi-schema-validator';
import { afterEach, describe, expect, it } from 'vitest';
import type { OpenApiDocument } from '../../src/openapi/types.js';
import { stableStringify } from '../../src/utils/stable-json.js';
import { rawRequest } from '../helpers/raw-http.js';
import { getFreePort } from '../helpers/ports.js';
import {
  startProxyHarness,
  startProxyOnly,
  waitFor,
  type ProxyHarness,
} from '../helpers/proxy-harness.js';

/**
 * Release blockers RB4 to RB10 and RB14, RB15.
 *
 * The document is built from real evidence written by a real proxy, then
 * validated against the official OpenAPI 3.1 schema — a hand-written
 * expectation would only prove the test agrees with the code.
 */

let harness: ProxyHarness;

afterEach(async () => {
  await harness.close();
});

async function validate(document: OpenApiDocument): Promise<void> {
  const validator = new Validator();
  const result = await validator.validate(document as unknown as Record<string, unknown>);

  if (result.valid !== true) {
    throw new Error(`invalid OpenAPI 3.1: ${JSON.stringify(result.errors)}`);
  }

  expect(validator.version).toBe('3.1');
}

async function post(path: string, body: unknown, headers: Record<string, string> = {}) {
  return rawRequest(`${harness.proxyOrigin}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...headers },
    body: Buffer.from(JSON.stringify(body)),
  });
}

describe('document root (RB4)', () => {
  it('produces a valid OpenAPI 3.1 document', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema`);
    await harness.waitForObservations(1);

    const document = harness.openApi.getDocument();

    await validate(document);

    expect(document.openapi).toBe('3.1.0');
    expect(document.info.version).toBe('0.0.0-observed');
    expect(document.info.description).toBe('Generated by WireQuill from observed HTTP traffic.');
    expect(document.servers).toEqual([{ url: harness.backend.origin }]);
    expect(document['x-wirequill'].source).toBe('observed-http-traffic');
  });

  it('is valid with no traffic at all', async () => {
    harness = await startProxyHarness();

    const document = harness.openApi.getDocument();

    await validate(document);
    expect(document.paths).toEqual({});
  });

  it('names the API after the target when nothing else is available', async () => {
    harness = await startProxyHarness();

    // The temporary project root has no package.json, so the fallback chain
    // ends at the directory name or the target host — never an absolute path.
    expect(harness.openApi.getDocument().info.title).not.toContain(':');
    expect(harness.openApi.getDocument().info.title.length).toBeGreaterThan(0);
  });
});

describe('paths and operations (RB5)', () => {
  it('documents a realistic API surface', async () => {
    harness = await startProxyHarness();

    await post('/auth/login', { email: 'a@example.com', password: 'p' });
    await rawRequest(`${harness.proxyOrigin}/products`);
    await rawRequest(`${harness.proxyOrigin}/products/123`);
    await post('/cart/items', { productId: 1, quantity: 2 });
    await post('/checkout', { total: 42.5 });
    await harness.waitForObservations(5);

    const document = harness.openApi.getDocument();
    await validate(document);

    expect(Object.keys(document.paths)).toEqual([
      '/auth/login',
      '/cart/items',
      '/checkout',
      '/products',
      '/products/{productId}',
    ]);

    expect(document.paths['/products/{productId}']?.get?.summary).toBe('Get Product');
    expect(document.paths['/products/{productId}']?.get?.operationId).toBe(
      'getProductsByProductId',
    );
    expect(document.paths['/auth/login']?.post?.summary).toBe('Login');
    expect(document.paths['/products']?.get?.tags).toEqual(['Products']);
  });

  it('materialises a path parameter with a synthetic example', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/products/987654`);
    await harness.waitForObservations(1);

    const parameters =
      harness.openApi.getDocument().paths['/products/{productId}']?.get?.parameters;

    expect(parameters).toEqual([
      {
        name: 'productId',
        in: 'path',
        required: true,
        schema: { type: 'integer' },
        example: '123',
      },
    ]);
    // The value a client actually sent is never the example.
    expect(JSON.stringify(parameters)).not.toContain('987654');
  });

  it('orders methods canonically within a path', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema`, { method: 'DELETE' });
    await rawRequest(`${harness.proxyOrigin}/schema`);
    await post('/schema', { a: 1 });
    await harness.waitForObservations(3);

    expect(Object.keys(harness.openApi.getDocument().paths['/schema'] ?? {})).toEqual([
      'get',
      'post',
      'delete',
    ]);
  });
});

describe('request bodies (RB6)', () => {
  it('documents a JSON body with schema and redacted example', async () => {
    harness = await startProxyHarness();

    await post('/echo', { id: 1, name: 'A', password: 'OPENAPI_PASSWORD_SECRET' });
    await harness.waitForObservations(1);

    const document = harness.openApi.getDocument();
    await validate(document);

    const media = document.paths['/echo']?.post?.requestBody?.content['application/json'];

    expect(media?.schema).toEqual({
      type: 'object',
      properties: {
        id: { type: 'integer' },
        name: { type: 'string' },
        password: { type: 'string' },
      },
    });
    expect(media?.example).toEqual({ id: 1, name: 'A', password: '[REDACTED]' });
  });

  it('never claims a request body is required', async () => {
    harness = await startProxyHarness();

    for (let index = 0; index < 4; index += 1) {
      await post('/echo', { id: index });
    }
    await harness.waitForObservations(4);

    const requestBody = harness.openApi.getDocument().paths['/echo']?.post?.requestBody;

    // Observed traffic shows a body was sent, never that one is mandatory.
    expect(requestBody).toBeDefined();
    expect(requestBody).not.toHaveProperty('required');
  });

  it('documents both media types an endpoint accepts', async () => {
    harness = await startProxyHarness();

    await post('/echo', { id: 1 });
    await rawRequest(`${harness.proxyOrigin}/echo`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: Buffer.from('name=Ada&tag=a&tag=b'),
    });
    await harness.waitForObservations(2);

    const content = harness.openApi.getDocument().paths['/echo']?.post?.requestBody?.content;

    expect(Object.keys(content ?? {})).toEqual([
      'application/json',
      'application/x-www-form-urlencoded',
    ]);
    expect(content?.['application/x-www-form-urlencoded']?.schema).toEqual({
      type: 'object',
      properties: {
        name: { type: 'string' },
        tag: { type: 'array', items: { type: 'string' } },
      },
    });
  });
});

describe('responses (RB7, RB9)', () => {
  it('keeps statuses and their schemas apart', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema`);
    await rawRequest(`${harness.proxyOrigin}/schema/missing`);
    await rawRequest(`${harness.proxyOrigin}/no-content`, { method: 'DELETE' });
    await harness.waitForObservations(3);

    const document = harness.openApi.getDocument();
    await validate(document);

    const ok = document.paths['/schema']?.get?.responses?.['200'];
    const missing = document.paths['/schema/missing']?.get?.responses?.['404'];
    const noContent = document.paths['/no-content']?.delete?.responses?.['204'];

    expect(ok?.description).toBe('Successful response');
    expect(ok?.content?.['application/json']?.schema).toHaveProperty('properties.active');

    expect(missing?.description).toBe('Not found');
    expect(missing?.content?.['application/json']?.schema).toHaveProperty('properties.error');

    expect(noContent?.description).toBe('No content');
    expect(noContent?.content).toBeUndefined();
  });

  it('excludes the 502 WireQuill generated for an unreachable target', async () => {
    const deadPort = await getFreePort();
    const proxy = await startProxyOnly(`http://127.0.0.1:${String(deadPort)}`);

    try {
      await rawRequest(`${proxy.proxyOrigin}/users`);
      await waitFor(() => proxy.observations.length > 0, 5_000, 'an observation');

      const document = proxy.openApi.getDocument();
      await validate(document);

      // The endpoint exists and was observed, but that 502 was WireQuill's, so
      // there is no response to document — and an empty `responses` object is
      // invalid OpenAPI 3.1.
      expect(document.paths['/users']?.get).toBeDefined();
      expect(document.paths['/users']?.get?.responses).toBeUndefined();
    } finally {
      await proxy.close();
    }

    harness = await startProxyHarness();
  });

  it('includes a 502 the backend really sent', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema/bad-gateway`);
    await harness.waitForObservations(1);

    const responses = harness.openApi.getDocument().paths['/schema/bad-gateway']?.get?.responses;

    expect(responses?.['502']?.description).toBe('Bad gateway');
    expect(responses?.['502']?.content?.['application/json']?.schema).toBeDefined();
  });

  it('sorts response codes numerically', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/status/500`);
    await rawRequest(`${harness.proxyOrigin}/status/200`);
    await rawRequest(`${harness.proxyOrigin}/status/404`);
    await harness.waitForObservations(3);

    const document = harness.openApi.getDocument();
    const statuses = Object.keys(
      document.paths['/status/{statusId}']?.get?.responses ??
        document.paths['/status/500']?.get?.responses ??
        {},
    );

    expect(statuses).toEqual([...statuses].sort((a, b) => Number(a) - Number(b)));
  });
});

describe('security (RB8)', () => {
  it('declares a bearer scheme and requires it once every sample used it', async () => {
    harness = await startProxyHarness();

    for (let index = 0; index < 3; index += 1) {
      await rawRequest(`${harness.proxyOrigin}/schema`, {
        headers: { Authorization: 'Bearer OPENAPI_TOKEN_SECRET' },
      });
    }
    await harness.waitForObservations(3);

    const document = harness.openApi.getDocument();
    await validate(document);

    expect(document.components?.securitySchemes).toEqual({
      bearerAuth: { type: 'http', scheme: 'bearer' },
    });
    expect(document.paths['/schema']?.get?.security).toEqual([{ bearerAuth: [] }]);
    expect(JSON.stringify(document)).not.toContain('OPENAPI_TOKEN_SECRET');
  });

  it('does not require auth when one call was anonymous', async () => {
    harness = await startProxyHarness();

    for (let index = 0; index < 3; index += 1) {
      await rawRequest(`${harness.proxyOrigin}/schema`, {
        headers: { Authorization: 'Bearer OPENAPI_TOKEN_SECRET' },
      });
    }
    await rawRequest(`${harness.proxyOrigin}/schema`);
    await harness.waitForObservations(4);

    const document = harness.openApi.getDocument();

    // The scheme is still described; the requirement is not claimed.
    expect(document.components?.securitySchemes).toHaveProperty('bearerAuth');
    expect(document.paths['/schema']?.get?.security).toBeUndefined();
  });

  it('never documents Authorization as a header parameter', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema`, {
      headers: { Authorization: 'Bearer OPENAPI_TOKEN_SECRET' },
    });
    await harness.waitForObservations(1);

    const parameters = harness.openApi.getDocument().paths['/schema']?.get?.parameters ?? [];

    expect(parameters.some((parameter) => parameter.in === 'header')).toBe(false);
  });
});

describe('leakage (RB14, RB15)', () => {
  it('carries no secret from a login exchange', async () => {
    harness = await startProxyHarness({ verbose: true });

    await post(
      '/auth/login',
      {
        email: 'openapi-secret@example.com',
        password: 'OPENAPI_PASSWORD_SECRET',
      },
      { Cookie: 'session=OPENAPI_COOKIE_SECRET' },
    );
    await harness.waitForObservations(1);

    const serialized = JSON.stringify(harness.openApi.getDocument());

    for (const secret of [
      'openapi-secret@example.com',
      'OPENAPI_PASSWORD_SECRET',
      'OPENAPI_COOKIE_SECRET',
    ]) {
      expect(serialized).not.toContain(secret);
    }

    // The types survived even though the values did not.
    const schema =
      harness.openApi.getDocument().paths['/auth/login']?.post?.requestBody?.content[
        'application/json'
      ]?.schema;

    expect(schema).toEqual({
      type: 'object',
      properties: {
        email: { type: 'string', format: 'email' },
        password: { type: 'string' },
      },
    });
  });

  it('carries no local filesystem path', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema`);
    await harness.waitForObservations(1);

    const serialized = JSON.stringify(harness.openApi.getDocument());

    // A document naming `D:\Project\Mine` would be unshareable.
    expect(serialized).not.toContain('\\\\');
    // A drive letter at a word boundary. Not simply `[A-Za-z]:/`, which the
    // `http://` in every server URL would match.
    expect(serialized).not.toMatch(/(?:^|[^A-Za-z0-9])[A-Za-z]:[\\/]/);
    expect(serialized).not.toContain('.wirequill');
    expect(serialized).not.toContain(harness.databasePath);
    expect(serialized).not.toContain('wirequill.sqlite');
  });

  it('carries no internal identifier', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema`);
    await harness.waitForObservations(1);

    const serialized = JSON.stringify(harness.openApi.getDocument());
    const observation = harness.observations.at(-1);

    expect(serialized).not.toContain(harness.workspaceId);
    expect(serialized).not.toContain(observation?.sessionId ?? 'session');
    expect(serialized).not.toContain(observation?.captureId ?? 'capture');
  });
});

describe('determinism (RB10)', () => {
  it('produces identical bytes from identical evidence', async () => {
    harness = await startProxyHarness();

    await post('/echo', { id: 1, name: 'A' });
    await rawRequest(`${harness.proxyOrigin}/schema`);
    await harness.waitForObservations(2);

    const first = stableStringify(harness.openApi.getDocument());
    const second = stableStringify(harness.openApi.getDocument());

    expect(second).toBe(first);
    // And insertion order matches too, not merely the canonical form.
    expect(JSON.stringify(harness.openApi.getDocument())).toBe(
      JSON.stringify(harness.openApi.getDocument()),
    );
  });

  it('hands out a fresh document each call', async () => {
    harness = await startProxyHarness();

    await rawRequest(`${harness.proxyOrigin}/schema`);
    await harness.waitForObservations(1);

    const document = harness.openApi.getDocument();
    document.info.title = 'MUTATED';

    // A caller cannot corrupt the cache for everyone else.
    expect(harness.openApi.getDocument().info.title).not.toBe('MUTATED');
  });
});
