import path from 'node:path';
import type { WireQuillConfig } from '../config/types.js';
import { normalizeTargetUrl } from '../config/target.js';
import type { StoredExample, StoredOperation } from '../storage/types.js';
import { buildPublicOperation, type BuildOperationOptions } from './build-operation.js';
import { titleCase } from './summaries.js';
import {
  METHOD_ORDER,
  type OpenApiDocument,
  type OpenApiPathItem,
  type OpenApiSecurityScheme,
} from './types.js';

/**
 * Assembles the OpenAPI document (spec sections 66 to 73).
 *
 * Reads operations and examples only. The observations table — potentially
 * twenty thousand rows — is never touched: everything the document needs was
 * folded into operation evidence when each request was processed.
 */

export interface BuildDocumentInput {
  config: WireQuillConfig;
  operations: readonly StoredOperation[];
  examplesByOperation: ReadonlyMap<string, StoredExample[]>;
  revision: number;
  options: BuildOperationOptions;
}

/**
 * Placeholder API version.
 *
 * The project's own `package.json` version is the version of the code, not of
 * the API it serves, and using it would be a claim WireQuill cannot support.
 */
export const OBSERVED_VERSION = '0.0.0-observed';

export const DOCUMENT_DESCRIPTION = 'Generated by WireQuill from observed HTTP traffic.';

export function buildDocument(input: BuildDocumentInput): OpenApiDocument {
  const paths: Record<string, OpenApiPathItem> = {};
  const securitySchemes: Record<string, OpenApiSecurityScheme> = {};

  for (const operation of input.operations) {
    const examples = input.examplesByOperation.get(operation.id) ?? [];
    const built = buildPublicOperation(operation, examples, input.options);

    const item = paths[built.path] ?? {};
    item[built.method] = built.operation;
    paths[built.path] = item;

    Object.assign(securitySchemes, built.securitySchemes);
  }

  const document: OpenApiDocument = {
    openapi: '3.1.0',
    info: {
      title: buildTitle(input.config),
      version: OBSERVED_VERSION,
      description: DOCUMENT_DESCRIPTION,
    },
    servers: [{ url: normalizeTargetUrl(input.config.target) }],
    paths: sortPaths(paths),
    'x-wirequill': { source: 'observed-http-traffic', revision: input.revision },
  };

  if (Object.keys(securitySchemes).length > 0) {
    document.components = { securitySchemes: sortRecord(securitySchemes) };
  }

  return document;
}

/**
 * Deterministic ordering (spec section 74).
 *
 * Paths lexicographically, methods in the canonical HTTP order. Two runs over
 * the same evidence must serialise to the same bytes, and JSON preserves
 * insertion order, so the order has to be built rather than hoped for.
 */
function sortPaths(paths: Record<string, OpenApiPathItem>): Record<string, OpenApiPathItem> {
  const sorted: Record<string, OpenApiPathItem> = {};

  for (const pathKey of Object.keys(paths).sort()) {
    const item = paths[pathKey];
    if (item === undefined) {
      continue;
    }

    const orderedItem: OpenApiPathItem = {};

    for (const method of METHOD_ORDER) {
      const operation = item[method];
      if (operation !== undefined) {
        orderedItem[method] = operation;
      }
    }

    // Anything outside the canonical list still gets in, after it.
    for (const method of Object.keys(item).sort()) {
      if (!METHOD_ORDER.includes(method)) {
        const operation = item[method];
        if (operation !== undefined) {
          orderedItem[method] = operation;
        }
      }
    }

    sorted[pathKey] = orderedItem;
  }

  return sorted;
}

function sortRecord<T>(record: Record<string, T>): Record<string, T> {
  const sorted: Record<string, T> = {};

  for (const key of Object.keys(record).sort()) {
    const value = record[key];
    if (value !== undefined) {
      sorted[key] = value;
    }
  }

  return sorted;
}

/**
 * Names the API (spec section 68).
 *
 * In order: what the user configured, the project's package name, the project
 * directory, and finally the target's hostname. Only the last is guaranteed to
 * exist, and none of them is an absolute path — a document that leaked
 * `D:\Project\Mine` would be unshareable.
 */
export function buildTitle(config: WireQuillConfig): string {
  const configured = config.docs.title;

  if (configured !== undefined && configured.trim() !== '') {
    return configured.trim();
  }

  const fromPackage = friendlyPackageName(config.sources.packageName);
  if (fromPackage !== null) {
    return fromPackage;
  }

  const directory = path.basename(config.sources.projectRoot);
  if (directory !== '' && directory !== '.' && !directory.includes(':')) {
    return `${titleCase(directory)} API`;
  }

  return `${config.target.hostname} API`;
}

/**
 * `@acme/backend-api` becomes `Acme Backend API`.
 *
 * A small deterministic reformat, not a naming engine: the scope becomes a
 * word, separators become spaces, and `api` keeps its conventional casing.
 */
export function friendlyPackageName(packageName: string | null): string | null {
  if (packageName === null || packageName.trim() === '') {
    return null;
  }

  const words = packageName
    .replace(/^@/, '')
    .split(/[/@._-]+/)
    .filter((part) => part !== '');

  if (words.length === 0) {
    return null;
  }

  const formatted = words.map((word) =>
    word.toLowerCase() === 'api'
      ? 'API'
      : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
  );

  return formatted.includes('API') ? formatted.join(' ') : `${formatted.join(' ')} API`;
}
