import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  majorOf,
  MINIMUM_NODE_MAJOR,
  nodeVersionError,
  requireSupportedNode,
} from '../../src/cli/require-node-version.js';

/**
 * What the published package promises about itself
 * (spec sections 14, 16, 17, 66 to 87 and 81).
 *
 * These are cheap assertions about files that are easy to change and easy to
 * forget: a licence field, an attribution file, an install script that should
 * not exist. None of them would fail a functional test, and every one of them
 * would be a problem in a published artifact.
 */

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const repoRoot = path.resolve(packageRoot, '..', '..');

interface Manifest {
  name?: string;
  license?: string;
  description?: string;
  keywords?: string[];
  files?: string[];
  bin?: Record<string, string>;
  engines?: Record<string, string>;
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
}

function manifest(directory: string): Manifest {
  return JSON.parse(readFileSync(path.join(directory, 'package.json'), 'utf8')) as Manifest;
}

function read(file: string): string {
  return readFileSync(file, 'utf8');
}

describe('licensing', () => {
  it('declares Apache-2.0 in both manifests', () => {
    expect(manifest(packageRoot).license).toBe('Apache-2.0');
    expect(manifest(repoRoot).license).toBe('Apache-2.0');
  });

  it('ships the full Apache License text', () => {
    const license = read(path.join(repoRoot, 'LICENSE'));

    expect(license).toContain('Apache License');
    expect(license).toContain('Version 2.0, January 2004');
    expect(license).toContain('TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION');
    expect(license).toContain('Copyright 2026 Gokhan OZGEZER');
    expect(license).not.toContain('MIT License');
  });

  it('ships a NOTICE with attribution', () => {
    const notice = read(path.join(repoRoot, 'NOTICE'));

    expect(notice).toContain('WireQuill');
    expect(notice).toContain('Copyright 2026 Gokhan OZGEZER');
    expect(notice).toContain('Apache License, Version 2.0');
  });

  it('keeps the packaged copies byte-identical to the repository ones', () => {
    // Generated by `scripts/sync-license.mjs` during the build, because npm can
    // only pack files that live inside the package directory. Two copies are a
    // drift risk; this is the check that makes the drift impossible to miss.
    for (const file of ['LICENSE', 'NOTICE']) {
      expect(existsSync(path.join(packageRoot, file)), `${file} must exist in the package`).toBe(
        true,
      );
      expect(read(path.join(packageRoot, file))).toBe(read(path.join(repoRoot, file)));
    }
  });

  it('no longer describes WireQuill itself as MIT-licensed', () => {
    for (const file of ['README.md', path.join('packages', 'wirequill', 'README.md')]) {
      // Word boundaries, because `LIMITATIONS.md` contains those three letters
      // and is not a licence claim.
      expect(read(path.join(repoRoot, file))).not.toMatch(/\bMIT\b/);
    }

    expect(read(path.join(repoRoot, 'README.md'))).toContain('Apache License 2.0');
  });
});

describe('published manifest', () => {
  const published = manifest(packageRoot);

  it('packs the interface, the licence and the notice', () => {
    expect(published.files).toContain('dist');
    expect(published.files).toContain('assets');
    expect(published.files).toContain('LICENSE');
    expect(published.files).toContain('NOTICE');
    expect(published.files).not.toContain('src');
    expect(published.files).not.toContain('test');
  });

  it('requires Node 24', () => {
    // Deliberate: `node:sqlite` is the storage engine, and it is what removes
    // the need for a native module and a compiler at install time.
    expect(published.engines?.node).toBe('>=24');
  });

  it('exposes exactly one binary', () => {
    expect(published.bin).toEqual({ wirequill: 'dist/cli.js' });
  });

  it('runs no install scripts', () => {
    // No surprise code execution at install time (spec section 67).
    for (const hook of ['preinstall', 'install', 'postinstall', 'prepare', 'prepublish']) {
      expect(published.scripts?.[hook], `${hook} must not exist`).toBeUndefined();
    }
  });

  it('has a description and honest keywords', () => {
    expect(published.description).toBeTruthy();
    expect(published.description?.length).toBeLessThan(120);
    expect(published.keywords).toContain('openapi');
    expect(published.keywords).toContain('documentation');
    expect((published.keywords ?? []).length).toBeLessThanOrEqual(12);
  });

  it('points at the real repository', () => {
    // This assertion used to say the opposite: before the repository existed,
    // the rule was that no `github.com` URL may appear at all, because an
    // invented one in a published manifest is worse than a missing one. The
    // repository exists now, so the rule becomes the exact addresses rather
    // than their absence — a manifest that points somewhere plausible but wrong
    // is the same failure in a new costume.
    const manifest = JSON.parse(read(path.join(packageRoot, 'package.json'))) as {
      repository?: {
        type?: string;
        url?: string;
      };
      bugs?: {
        url?: string;
      };
      homepage?: string;
    };

    expect(manifest.repository).toEqual({
      type: 'git',
      url: 'git+https://github.com/gokhanozgezer/wirequill.git',
    });

    expect(manifest.bugs).toEqual({
      url: 'https://github.com/gokhanozgezer/wirequill/issues',
    });

    expect(manifest.homepage).toBe('https://github.com/gokhanozgezer/wirequill#readme');
  });

  it('depends on nothing that needs a compiler', () => {
    // Every runtime dependency is pure JavaScript. A native module would drag
    // node-gyp, Python and Visual Studio Build Tools into a Windows install
    // (spec sections 68 and 122).
    expect(Object.keys(published.dependencies ?? {}).sort()).toEqual([
      'commander',
      'http-proxy-middleware',
      'open',
      'picocolors',
      'zod',
    ]);
  });
});

describe('node version guard', () => {
  it('accepts the supported runtime', () => {
    expect(nodeVersionError(`v${String(MINIMUM_NODE_MAJOR)}.14.0`)).toBeNull();
    expect(nodeVersionError('v25.0.0')).toBeNull();
    expect(nodeVersionError(process.version)).toBeNull();
  });

  it('explains an unsupported runtime instead of failing on a built-in', () => {
    const message = nodeVersionError('v22.11.0');

    expect(message).toContain('WireQuill requires Node.js 24 or newer.');
    expect(message).toContain('Current version: v22.11.0');
    // The reason, not just the rule.
    expect(message).toContain('SQLite');
    expect(message).not.toContain('ERR_UNKNOWN_BUILTIN_MODULE');
  });

  it('writes the message and reports failure', () => {
    const lines: string[] = [];

    expect(requireSupportedNode('v20.0.0', (line) => lines.push(line))).toBe(false);
    expect(lines.join('\n')).toContain('WireQuill requires Node.js 24 or newer.');

    expect(requireSupportedNode('v24.0.0', (line) => lines.push(line))).toBe(true);
  });

  it('does not refuse a version it cannot parse', () => {
    // A custom build with an unusual version string is not a reason to stop.
    expect(nodeVersionError('nightly')).toBeNull();
    expect(majorOf('nightly')).toBeNull();
    expect(majorOf('v24.14.0')).toBe(24);
    expect(majorOf('24.0.0')).toBe(24);
  });
});
